### ISSUE TITLE
Unable to install with Package Control

### ISSUE THREAD

**Issue by ghost** [hktonylee/SublimeNumberKing#1]
Unable to install with Package Control

It's missing from the list of available packages

**Comment by hktonylee** [comment]
Thanks for reporting! Let me have a look first.

#### Update (2014-02-12)

I guess it is the problem of semantic versioning. Let me check the tag and try it later.

**Comment by hktonylee** [comment]
I fixed the semantic versioning ;-) I used `0.0.3-development` which is a bad version tag.
