### ISSUE TITLE
ValueError: could not convert string to float, when run `King: Number Sequence`

### ISSUE THREAD

**Issue by evandrocoan** [hktonylee/SublimeNumberKing#3]
### ValueError: could not convert string to float, when run `King: Number Sequence` 

How to reproduce it:

1. Create multi selections. 
![image](https://cloud.githubusercontent.com/assets/5332158/20365670/ea30aa90-ac2e-11e6-90d5-05b47c2143c8.png)
1. Open the command palette.
1. Run the King: Number Sequence command.

       "caption": "King: Number Sequence",
        "command": "king_manipulate_number",

```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Number King.sublime-package\core\number.py", line 45, in run
ValueError: could not convert string to float: 
```

**Comment by hktonylee** [comment]
Thanks for report! Let me find some time to fix it

**Comment by hktonylee** [comment]
Fix with commit https://github.com/hktonylee/SublimeNumberKing/commit/465d23150853442df8ff033bac2f20ead8dc2cfc

Please wait for the sublime package control to pull the repo ;-)

**Comment by evandrocoan** [comment]
Thanks.

**Comment by hktonylee** [comment]
You're welcome ;-)
